# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruit', '0101_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('apple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.Apple')),
            ],
        ),
    ]
