# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_cranberry_bacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='size',
            field=models.IntegerField(default=3),
        ),
    ]
