# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_apple_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cranberry',
            name='bacon',
            field=models.IntegerField(db_column='bacon_id', null=True),
        ),
    ]
