# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('meat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cranberry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bacon', models.IntegerField(db_column='bacon_id', null=True)),
            ],
        ),
    ]
