# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'fruit', '0002_cranberry_bacon'), (b'fruit', '0100_prepare_squash')]

    initial = True

    dependencies = [
        ('fruit', '0001_initial'),
        ('meat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cranberry',
            name='bacon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meat.Bacon'),
        ),
    ]
