# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0102_relink_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cranberry',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
